version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run:
          name: Print pipeline ID
          command: echo $CIRCLE_WORKFLOW_ID

jobs:
  print_pipeline_id_job:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print pipeline ID
          command: print_pipeline_id

workflows:
  print_pipeline_id_workflow:
    jobs:
      - print_pipeline_id_job
