version: 2.1

orbs:
  # Choose either one of the orbs below
  welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
jobs:
  create_infrastructure: 
    executor: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "AnsibleDemo"
      - run:
          name: Install ansible
          command: |
            apk add --update ansible
      - run:
          name: Configure EC2 instance
          command: |
            ansible-playbook -i inventory main-remote.yml

workflows:
  myWorkflow:
    jobs:
      - create_infrastructure
