# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

jobs:
  print_hello: # name of your job
    docker: # executor type
      - image: cimg/base:stable # primary container will run the latest, production-ready base image
    steps:
      - run: echo "hello"

  print_world: # name of your job
    docker: # executor type
      - image: cimg/base:stable # primary container will run the latest, production-ready base image
    steps:
      - run: echo "world"

  print_name: # name of your job
    docker: # executor type
      - image: cimg/base:stable # primary container will run the latest, production-ready base image
    environment:
      MY_ENV_VAR: Benedict Adu
    steps:
      - run: echo "My name is $MY_ENV_VAR"

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_name:
          requires:
            - print_world

